version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - bash create.sh
    finally:
      - echo "Remove old containers"
      - docker rm -f $(docker ps -aq) || true
artifacts:
  files:
    - deploy/build.log
    - deploy/image_*-K3S-RPI-custom.zip
  discard-paths: yes
