version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - bash create.sh
artifacts:
  files:
    - deploy/build.log
    - deploy/image_*-K3S-RPI-custom.zip
  discard-paths: yes
